import { useState } from "react";
import Head from "next/head"
import Image from "next/image"
import { useRouter } from "next/router";
import Form from "../Components/Form/Form";
import Footer from "../Components/Footer/Footer"
import style from "../Components/Form/form.module.css"
import styles from "../styles/container.module.css";

function AddBirthday() {
  const router = useRouter();
  const [values, setValues] = useState({
    firstName: "",
    lastName: "",
    email: "",
    birthday: "",
  });
  
  const handleInputChange = function (e) {
    const eTargetName = e.target.name;
    const value = e.target.value;
    setValues({ ...values, [eTargetName]: value });
  };

  const handleSubmit = (e) => {
    fetch("https://birthday-app-api.vercel.app/api/v1/john/birthdays/add", {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        firstName: values.firstName,
        lastName: values.lastName,
        email: values.email,
        birthday: values.birthday,
      }),
    })
      .then((response) => {
        if (response.ok) {
          alert("Birthday saved!");
          response.json();
          return router.push("/birthdays");
        }
      })
      .catch((error) => {
        alert("An error has occurred, please try again later");
      });
  };

  return (
    <div className={styles.containerApp_form}>
      <Head>
        <title>Birthday App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cake.ico" />
      </Head>
      <Form
        onSubmit={(e) => {
          e.preventDefault();
          handleSubmit(e);
        }}
        onChange={(e) => handleInputChange(e)}
        values={values}
        title={"¡Add a birthday to your list!"}
      ></Form>
      <Footer/>
    </div>
  );
}

export default AddBirthday;
