import Head from 'next/head'

function Birthdays() {

 
  return (
        <div>
        <Head>
            <title>Birthday App</title>
            <meta name="description" content="Generated by create next app" />
            <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;500&display=swap" rel="stylesheet"/>
            <link rel="icon" href="/cake.ico" />
        </Head>
            <h1>Ola k ase aca van los cumples</h1>
        </div>
    )
}

export default Birthdays;