import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/container.module.css";
import { AnchorPrimary } from "../Components/AnchorsButton/Anchor";

function Home() {
	return (
		<div background="white">
			<Head>
				<title>Birthday App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/cake.ico" />
			</Head>

			<main className={styles.containerApp}>
				<Image
					src="/boxHappy.svg"
					width={350}
					height={350}
					alt="Image not found"
				/>
				<Link href="/terms" passHref>
					<AnchorPrimary name="Log in" />
				</Link>
			</main>
		</div>
	);
}

export default Home;
