import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {

    fetch('')
  return (
    <div className={styles.container}>
      <Head>
        <title>Birthday App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cake.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/boxHappy.svg"
          width={350}
          height={350}
        />
        <Link href="/terms">
        <a >
          Log in
        </a>
        </Link>


      </main>
    </div>
  )
}
