import React from "react";
import Head from "next/head";
import SignUp from "../Components/SignUp/SignUp";
import Footer from "../Components/Footer/Footer";
import { Anchor } from "../Components/AnchorsButton/Anchor";
import styles from "../Components/SignUp/signon.module.css";

function Home() {
  return (
    <>
      <Head>
        <title>Birthday App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cake.ico" />
      </Head>
      <main className={styles.container}>
        <section className={styles.container_text_sign_up}>
          <h1>Create account</h1>
          <p className={styles.record_paragraph}>
            Birthday App is an application for you to store, manage and consult
            all the birthdays that you will have soon, in an orderly manner and
            even send your greetings. <br />
          </p>
          <div className={styles.container_log_in}>
            <strong>¿You have account?</strong>
            <Anchor to="sign-in" name="Log In" variant="secondary" />
          </div>
        </section>

        <SignUp />
      </main>
        <div className={styles.container_log_in_mobile}>
          <strong>¿You have account?</strong>
          <Anchor to="sign-in" name="Log In" variant="secondary" />
        </div>
      <Footer />
    </>
  );
}

export default Home;
