import React from "react";
import Head from "next/head";
import SignUp from "../Components/SignUp/SignUp";

function SignIn() {
  return (
    <div>
      <Head>
        <title>Birthday App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cake.ico" />
      </Head>

      <main>
        <p>Nueva ruta para LogIn</p>
      </main>
    </div>
  );
}

export default SignIn;
