import React from "react";
import Head from "next/head";
import Footer from "../Components/Footer/Footer"

function SignIn() {
  return (
    <div>
      <Head>
        <title>Birthday App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cake.ico" />
      </Head>

      <main>
        <p>Nueva ruta para LogIn</p>
      </main>
      <Footer/>
    </div>
  );
}

export default SignIn;
