import React from "react";
import Head from "next/head";
import LogIn from "../Components/LogIn/LogIn";
import { Anchor } from "../Components/AnchorsButton/Anchor";
import Footer from "../Components/Footer/Footer";
import style from "../Components/LogIn/signin.module.css";

function SignIn() {
  return (
    <>
      <Head>
        <title>Birthday App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cake.ico" />
      </Head>

      <main className={style.container_login}>
        <section className={style.container_text_login}>
          <h1>Stay present with Birthday App</h1>
          <p className={style.record_paragraph}>
            Birthday App is an application for you to store, manage and consult
            all the birthdays that you will have soon, in an orderly manner and
            even send your greetings. <br />
          </p>
          <div className={style.container_signup}>
            <strong>¿You do not have an account?</strong>
            <Anchor to="/" name="Sign Up" variant="secondary" />
          </div>
        </section>
        <LogIn />
      </main>
      <Footer />
    </>
  );
}

export default SignIn;