import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import container from "../styles/container.module.css";
import terms from "../styles/terms.module.css";
import { Anchor } from "../Components/AnchorsButton/Anchor";
import { useRouter } from "next/router";
import Button from "../Components/Button/Button";

function Terms() {
  const router = useRouter();
  const [buttonActive, setButtonActive] = useState(true);

  return (
    <div className={container.containerApp}>
      <Head>
        <title>Birthday App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;500&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/cake.ico" />
      </Head>

      <main className={container.container_content}>
          <h1 className={terms.terms_title}>Hello name of user</h1>
        <div className={terms.terms_instructions}>
  
          <h5>Author: Joel Durand</h5>
          <p className={terms.terms_paragraph}>
            <strong>Exercitation ullamco:</strong> <br/>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. <br/>
            - Quis nostrud exercitation ullamco laboris <br/>
            - Quis nostrud exercitation ullamco laboris <br/>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. <br/>
            <strong>Tempor incididunt ut labore:</strong>  <br/>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. <br/>
            <strong>Exercitation ullamco:</strong> <br/>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. <br/>
            - Quis nostrud exercitation ullamco laboris <br/>
            - Quis nostrud exercitation ullamco laboris <br/>
            - Quis nostrud exercitation ullamco laboris <br/>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. <br/>
            <strong>Tempor incididunt ut labore:</strong>  <br/>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat.
          </p>
        <section className={terms.section}>
          <input
            type="checkbox"
            id="terms"
            onChange={() => setButtonActive(!buttonActive)}
          />
          <label className={terms.label} htmlFor="terms">
            Terms and Conditions
          </label>
        </section>
        </div>

        <footer className={terms.navBarSecondary}>
          <Anchor name="Decline" to="/" variant="cancel" />

          <Button
            disabled={buttonActive}
            name={"Accept"}
            onClick={() => {
              router.push("/birthdays");
            }}
          />
        </footer>
      </main>
    </div>
  );
}

export default Terms;
