import Head from 'next/head'
import Image from 'next/image' 

function Terms() {
 
    return (
          <div>
            <Head>
                <title>Birthday App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/cake.ico" />
            </Head>
                <h1>Hello "nombre del user"</h1>
                <Image 
                src='/cake.svg'
                width={350}
                height={350}
                />
                <h2>Lorem ipsum sit amet. Lorem ipsum sit amet. Lorem ipsum sit amet.
                </h2>
                <h4>Author: Joel Durand</h4>
                <input type='checkbox'/> <a>Terms and Conditions</a> <br/>
                    <button>Decline</button>
                    <button>Accept</button>
          </div>
      )
  }
  
  export default Terms;