import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Boxes.module.css";
import buttons from "../styles/Buttons.module.css";

function Terms() {
	return (
		<div>
			<Head>
				<title>Birthday App</title>
				<meta name="description" content="Generated by create next app" />
				<link
					href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;500&display=swap"
					rel="stylesheet"
				/>
				<link rel="icon" href="/cake.ico" />
			</Head>

			<main className={styles.terms}>
                <div className={styles.instructions}>
					<h1>Hello "name of user"</h1>
					<Image src="/cake.svg" width={350} height={350} />
					<h4>Author: Joel Durand</h4>
					<p className={styles.paragraph}>
						Lorem ipsum sit amet. Lorem ipsum sit amet. Lorem ipsum sit amet.
                        Lorem ipsum sit amet. Lorem ipsum sit amet. Lorem ipsum sit amet.
                        Lorem ipsum sit amet. Lorem ipsum sit amet. Lorem ipsum sit amet.
                        Lorem ipsum sit amet. Lorem ipsum sit amet. Lorem ipsum sit amet.
					</p>
				</div>

                    <section className={styles.section}>

                <input type="checkbox" /> <a>Terms and Conditions</a>
                    </section>
				<footer className={styles.form}>
					<Link href="/">
						<a className={buttons.button_cancel}>Decline</a>
					</Link>
					<Link href="/birthdays">
						<a className={buttons.button_primary}>Accept</a>
					</Link>
				</footer>
			</main>
		</div>
	);
}

export default Terms;
